# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WvsvP6f-BGbwzMeXWibmcmoX9KNd6Xu
"""



"""addition of two number"""

a=10
b=20
c=a+b
print(c)